WORKING_DIR: ""


MODEL:
  TYPE: "human_detector"
  PACKAGE: "yolo"
  MODULE: "YoloModel"

DATASET:
  TRAIN: "train_crowd"
  TEST: "test_crowd"
  DATA_PATH: "data"
  TEST_VIDEO: "input/video1.mp4"
  SAVE_PATH: "output/video1.mp4"

